server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

token:
  secret: GachonUniversity2023KAKAO2023ENTERPRISE2023ACADEMY2023VER02TEAM10KAFEine2018jin2019mo2020gina2020dokyung2019imaeFastTrackLetsGo
  access-expiration-time: 1800000
  refresh-expiration-time: 18000000

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/auth/signup
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/auth/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/api/member/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: wspace-service
          uri: lb://WSPACE-SERVICE
          predicates:
            - Path=/api/wspace/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: enq-service
          uri: lb://ENQ-SERVICE
          predicates:
            - Path=/api/enq/**, /api/sbox/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: ans-service
          uri: lb://ANS-SERVICE
          predicates:
            - Path=/api/ans/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/api/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
